//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicle_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plan_quantities
    {
        public int pqid { get; set; }
        public int plan_quantity { get; set; }
        public System.DateTime plan_datetime { get; set; }
        public int mid { get; set; }
        public int loginid { get; set; }
    
        public virtual Login Login { get; set; }
        public virtual modal_details modal_details { get; set; }
    }
}
