//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicle_Management_System.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VMSEntities : DbContext
    {
        public VMSEntities()
            : base("name=VMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<approve_quantities> approve_quantities { get; set; }
        public virtual DbSet<dispatch_quantities> dispatch_quantities { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<modal_details> modal_details { get; set; }
        public virtual DbSet<plan_quantities> plan_quantities { get; set; }
    }
}
